Repository PacketFabric/terraform-provider-packetfabric, pull requests merged in 2022-12, with the labels that each got.

#289 Skip TestAccIBMHostedConnection
  internal/provider/resource_hosted_ibm_conn_test.go
Labels: acceptance test

#287 208: Datasource packetfabric_port_router_logs
  docs/data-sources/packetfabric_port_router_logs.md
  docs/resources/packetfabric_link_aggregation_group.md
  examples/data-sources/packetfabric_port_router_logs/data-source.tf
  examples/main.tf
  examples/resources/packetfabric_link_aggregation_group/resource.tf
  internal/packetfabric/interfaces.go
  internal/provider/datasource_port_router_logs.go
  internal/provider/provider.go
  templates/data-sources/port_router_logs.md.tmpl
Labels: new feature

#274 #203: Datasource packetfabric_locations_pop_zones
  docs/data-sources/packetfabric_locations_pop_zones.md
  examples/data-sources/packetfabric_locations_pop_zones/data-source.tf
  examples/main.tf
  internal/packetfabric/locations.go
  internal/provider/datasource_zones.go
  internal/provider/provider.go
  templates/data-sources/locations_pop_zones.md.tmpl
Labels: new feature

#291 Add media arg to GetPopAndZoneWithAvailablePort
  internal/provider/datasource_port_availability_test.go
  internal/provider/datasource_port_device_info_test.go
  internal/provider/datasource_port_vlan_summary_test.go
  internal/provider/resource_ix_vc_test.go
  internal/provider/resource_port_loa_test.go
  internal/provider/resource_port_test.go
  internal/provider/resource_third_party_virtual_circuit_test.go
  internal/testutil/testutil.go
Labels: acceptance test

#294 199: Resource packetfabric_billing_modify_order
  docs/data-sources/packetfabric_locations_cloud.md
  docs/data-sources/packetfabric_port_router_logs.md
  docs/resources/packetfabric_billing_modify_order.md
  examples/main.tf
  examples/resources/packetfabric_billing_modify_order/resource.tf
  internal/packetfabric/billing.go
  internal/provider/provider.go
  internal/provider/resource_billing.go
  templates/data-sources/locations_cloud.md.tmpl
  templates/data-sources/locations_pop_zones.md.tmpl
  templates/data-sources/port_router_logs.md.tmpl
  templates/resources/billing_modify_order.md.tmpl
Labels: new feature

#299 Contributing update
  CONTRIBUTING.md
Labels: documentation

#293 209: Adding resource packetfabric_port_status
  docs/resources/packetfabric_port.md
  examples/main.tf
  examples/resources/packetfabric_port/resource.tf
  internal/packetfabric/interfaces.go
  internal/provider/resource_ports.go
Labels: new feature

#277 Add environment variables for Cloud Providers Account information
  CHANGELOG.md
  docs/index.md
  docs/resources/packetfabric_cloud_router_bgp_session.md
  docs/resources/packetfabric_cloud_router_connection_aws.md
  docs/resources/packetfabric_cs_aws_hosted_connection.md
  docs/resources/packetfabric_cs_aws_hosted_marketplace_connection.md
  docs/resources/packetfabric_marketplace_service_accept_request.md
  docs/resources/packetfabric_marketplace_service_reject_request.md
  examples/README.md
  examples/main.tf
  examples/provider/provider.tf
  examples/resources/packetfabric_cloud_router_bgp_session/resource.tf
  examples/resources/packetfabric_cloud_router_connection_aws/resource.tf
  examples/resources/packetfabric_cs_aws_hosted_connection/resource.tf
  examples/resources/packetfabric_cs_aws_hosted_marketplace_connection/resource.tf
  examples/resources/packetfabric_marketplace_service_accept_request/resource.tf
  examples/resources/packetfabric_marketplace_service_reject_request/resource.tf
  examples/source_env_var.sh.sample
  examples/test_prod_dev.sh
  examples/use-cases/README.md
  examples/use-cases/backbone_virtual_circuit/main.tf
  examples/use-cases/backbone_virtual_circuit_mesh/main.tf
  examples/use-cases/cloud_router_aws/README.md
  examples/use-cases/cloud_router_aws/cloud_router_connections.tf
  examples/use-cases/cloud_router_aws/provider.tf
  examples/use-cases/cloud_router_aws/variables.tf
  examples/use-cases/cloud_router_aws_google/README.md
  examples/use-cases/cloud_router_aws_google/cloud_router_connection_aws.tf
  examples/use-cases/cloud_router_aws_google/cloud_router_connection_google.tf
  examples/use-cases/cloud_router_aws_google/provider.tf
  examples/use-cases/cloud_router_aws_google/variables.tf
  examples/use-cases/cloud_router_google_azure/README.md
  examples/use-cases/cloud_router_google_azure/cloud_router_connection_google.tf
  examples/use-cases/cloud_router_google_azure/provider.tf
  examples/use-cases/cloud_router_google_azure/variables.tf
  examples/use-cases/cloud_router_google_ipsec/README.md
  examples/use-cases/cloud_router_google_ipsec/cloud_router_connection_google.tf
  examples/use-cases/cloud_router_google_ipsec/provider.tf
  examples/use-cases/cloud_router_google_ipsec/variables.tf
  examples/use-cases/cloud_router_ibm_oracle/provider.tf
  examples/use-cases/dedicated_cloud_aws/README.md
  examples/use-cases/dedicated_cloud_aws/main.tf
  examples/use-cases/hosted_cloud_aws/README.md
  examples/use-cases/hosted_cloud_aws/main.tf
  examples/use-cases/hosted_cloud_aws/variables.tf
  examples/use-cases/hosted_cloud_azure/main.tf
  examples/use-cases/hosted_cloud_google/README.md
  examples/use-cases/hosted_cloud_google/main.tf
  examples/use-cases/hosted_cloud_google/variables.tf
  examples/use-cases/marketplace/a_side/main.tf
  examples/use-cases/marketplace/z_side/main.tf
  examples/variables.tf
  internal/provider/resource_aws_cloud_router_connection.go
  internal/provider/resource_aws_hosted_mkt.go
  internal/provider/resource_aws_request_hosted_conn.go
  templates/resources/billing_modify_order.md.tmpl
Labels: enhancement

#300 Changelog v0.5
  CHANGELOG.md
Labels: documentation

#298 PSE-10317: add dnat_capable to cr connection response
  docs/data-sources/packetfabric_cloud_router_connections.md
  internal/packetfabric/cloud_router_connection.go
  internal/packetfabric/cloud_router_connection_test.go
  internal/provider/datasource_cloud_conn.go
Labels: enhancement

#292 Fix/283: Fix context cancelled for Cloud Router Connection Read
  internal/packetfabric/client.go
  internal/provider/resource_backbone.go
Labels: bugfix

#297 fix/266 Delete Error: could not find BGP session associated with the provided Cloud Router ID: Status: 404
  internal/provider/resource_bgp_session.go
Labels: bugfix

#303 Add lifecycle/ignore_changes to examples/main.tf
  examples/main.tf
Labels: documentation

#304 Adding PF_ACC_TEST_IX_ROUTING_ID and PF_ACC_TEST_IX_MARKET
  README.md
  internal/provider/resource_ix_vc_test.go
Labels: acceptance test

#305 Shuffle locations list in acc tests
  internal/testutil/testutil.go
Labels: acceptance test
