Repository PacketFabric/terraform-provider-packetfabric, pull requests merged in 2022-11, with the labels that each got.

#194 PSE-10014: update cr connection response
  internal/packetfabric/cloud_router_connection.go
  internal/packetfabric/cloud_router_connection_test.go
  internal/provider/datasource_cloud_conn.go
Labels: enhancement, pending PF release

#232 Fix/229: Cannot destroy packetfabric_cs_oracle_hosted connection.
  internal/packetfabric/cloud_service_aws.go
Labels: bugfix

#231 Fix/227: Fix interface conversion. Change ibm_bgp_asn type to INT.
  internal/provider/resource_ibm_route_cloud_connection.go
Labels: bugfix

#224 Remove packetfabric_cloud_router_bgp_prefixes
  examples/data-sources/packetfabric_cloud_router_bgp_prefixes/data-source.tf
  examples/resources/packetfabric_cloud_router_bgp_prefixes/resource.tf
  internal/provider/provider.go
  internal/provider/resource_bgp_session.go
  templates/data-sources/cloud_router_bgp_prefixes.md.tmpl
  templates/resources/cloud_router_bgp_prefixes.md.tmpl
  templates/resources/cloud_router_bgp_session.md.tmpl
Labels: enhancement

#214 Check if marketplace request is on pending state before delete.
  internal/packetfabric/cloud_service_aws.go
  internal/provider/resource_aws_hosted_mkt.go
  internal/provider/resource_azure_hosted_mkt_conn.go
  internal/provider/resource_google_hosted_mkt_conn.go
  internal/provider/resource_oracle_mkt_cloud_conn.go
  internal/provider/resource_third_party_virtual_circuit.go
Labels: enhancement, new feature

#226 Fix runtime error.
  internal/packetfabric/point_to_point.go
  internal/packetfabric/vc_backbone.go
  internal/provider/resource_point_to_point.go
Labels: bugfix

#223 Feature/155: New packetfbric_marketplace_service_accept_request/reject resources.
  internal/packetfabric/cloud_service_aws.go
  internal/packetfabric/interfaces.go
  internal/packetfabric/service_provision.go
  internal/provider/provider.go
  internal/provider/resource_provision_mkt.go
  internal/provider/resource_provision_requested_service.go
  internal/provider/resource_reject_requested_service.go
Labels: new feature

#239 Fix/238: Fix error when trying to update VC Backbone.
  internal/packetfabric/cloud_service_aws.go
  internal/provider/resource_add_speed_burst.go
  internal/provider/resource_backbone.go
  internal/provider/resource_ix_vc.go
  internal/provider/resource_vc_backbone.go
Labels: bugfix

#247 Doc fixes for issues #241 and #243
  docs/data-sources/packetfabric_marketplace_requests.md
  docs/data-sources/packetfabric_marketplace_service_requests.md
  docs/guides/getting_started.md
  docs/index.md
  templates/data-sources/marketplace_service_requests.md.tmpl
  templates/guides/getting_started.md
  templates/index.md.tmpl
Labels: documentation

#245 Adding new test for cloud_router_connection_aws resource
  README.md
  internal/provider/resource_aws_cloud_router_connection.go
  internal/provider/resource_aws_cloud_router_connection_test.go
  internal/provider/resource_cloud_router_test.go
Labels: acceptance test

#259 Add support Terraform Import to hosted/dedicated cloud
  docs/resources/packetfabric_cs_aws_dedicated_connection.md
  docs/resources/packetfabric_cs_aws_hosted_connection.md
  docs/resources/packetfabric_cs_google_hosted_connection.md
  docs/resources/packetfabric_cs_oracle_hosted_connection.md
  docs/resources/packetfabric_point_to_point.md
  internal/provider/resource_aws_request_dedicated_conn.go
  internal/provider/resource_aws_request_hosted_conn.go
  internal/provider/resource_google_request_hosted_conn.go
  internal/provider/resource_oracle_hosted_conn.go
  templates/resources/cs_aws_dedicated_connection.md.tmpl
  templates/resources/cs_aws_hosted_connection.md.tmpl
  templates/resources/cs_google_hosted_connection.md.tmpl
  templates/resources/cs_oracle_hosted_connection.md.tmpl
  templates/resources/point_to_point.md.tmpl
Labels: enhancement

#242 Remove zone from packetfabric_cs_azure_hosted_marketplace_connection
  docs/resources/packetfabric_cs_azure_hosted_marketplace_connection.md
  internal/packetfabric/cloud_service_azure.go
  internal/provider/resource_azure_hosted_mkt_conn.go
Labels: bug

#261 PSE-10145 is_awaiting_onramp
  CONTRIBUTING.md
  docs/data-sources/packetfabric_cs_aws_dedicated_connection.md
  docs/data-sources/packetfabric_cs_aws_hosted_connection.md
  docs/data-sources/packetfabric_cs_azure_hosted_connection.md
  docs/data-sources/packetfabric_cs_google_hosted_connection.md
  docs/data-sources/packetfabric_cs_oracle_hosted_connection.md
  docs/resources/packetfabric_cs_aws_hosted_connection.md
  docs/resources/packetfabric_cs_google_hosted_connection.md
  internal/packetfabric/cloud_service_aws.go
  internal/packetfabric/cloud_service_aws_test.go
  internal/provider/datasource_cloud_service_aws.go
  templates/resources/cs_aws_hosted_connection.md.tmpl
  templates/resources/cs_aws_hosted_marketplace_connection.md.tmpl
  templates/resources/cs_google_hosted_connection.md.tmpl
  templates/resources/cs_google_hosted_marketplace_connection.md.tmpl
Labels: enhancement

#265 Update BGP session update function with PUT instead of PATCH
  internal/packetfabric/bgp_session.go
Labels: bugfix

#262 Simplify dedicated cloud connections
  docs/data-sources/packetfabric_cs_aws_dedicated_connection.md
  docs/data-sources/packetfabric_cs_dedicated_connections.md
  docs/data-sources/packetfabric_cs_google_dedicated_connection.md
  docs/resources/packetfabric_cs_azure_dedicated_connection.md
  docs/resources/packetfabric_cs_google_dedicated_connection.md
  examples/data-sources/packetfabric_cs_aws_dedicated_connection/data-source.tf
  examples/data-sources/packetfabric_cs_azure_dedicated_connection/data-source.tf
  examples/data-sources/packetfabric_cs_dedicated_connections/data-source.tf
  examples/data-sources/packetfabric_cs_google_dedicated_connection/data-source.tf
  examples/main.tf
  internal/provider/provider.go
  templates/data-sources/cs_aws_dedicated_connection.md.tmpl
  templates/data-sources/cs_azure_dedicated_connection.md.tmpl
  templates/data-sources/cs_dedicated_connections.md.tmpl
  templates/data-sources/cs_google_dedicated_connection.md.tmpl
Labels: enhancement

#282 Add delay to cloud router destroy in acc tests
  internal/provider/provider_test.go
  internal/provider/resource_aws_cloud_router_connection_test.go
  internal/provider/resource_cloud_router_test.go
Labels: acceptance test

#283 Rename PF_ACCOUNT_UUID to PF_ACCOUNT_ID in ACC
  README.md
  internal/testutil/testutil.go
Labels: acceptance test

#271 #201: Datasource packetfabric_locations_regions
  docs/data-sources/packetfabric_cs_azure_hosted_connection.md
  docs/data-sources/packetfabric_cs_dedicated_connections.md
  docs/data-sources/packetfabric_locations_regions.md
  docs/index.md
  docs/resources/packetfabric_cloud_router.md
  docs/resources/packetfabric_cloud_router_bgp_session.md
  docs/resources/packetfabric_cloud_router_connection_aws.md
  docs/resources/packetfabric_cloud_router_connection_azure.md
  docs/resources/packetfabric_cloud_router_connection_google.md
  docs/resources/packetfabric_cloud_router_connection_ibm.md
  docs/resources/packetfabric_cloud_router_connection_ipsec.md
  docs/resources/packetfabric_cloud_router_connection_oracle.md
  docs/resources/packetfabric_cloud_router_connection_port.md
  docs/resources/packetfabric_cs_aws_dedicated_connection.md
  docs/resources/packetfabric_cs_oracle_hosted_connection.md
  docs/resources/packetfabric_cs_oracle_hosted_marketplace_connection.md
  docs/resources/packetfabric_point_to_point.md
  examples/data-sources/packetfabric_locations_regions/data-source.tf
  examples/resources/packetfabric_backbone_virtual_circuit/resource.tf
  examples/resources/packetfabric_backbone_virtual_circuit_marketplace/resource.tf
  examples/resources/packetfabric_cloud_router_connection_google/resource.tf
  examples/resources/packetfabric_cloud_router_connection_ipsec/resource.tf
  examples/resources/packetfabric_cloud_router_connection_oracle/resource.tf
  examples/resources/packetfabric_cloud_router_connection_port/resource.tf
  examples/resources/packetfabric_ix_virtual_circuit_marketplace/resource.tf
  examples/resources/packetfabric_point_to_point/resource.tf
  internal/packetfabric/regions.go
  internal/provider/datasource_locations_regions.go
  internal/provider/datasource_locations_regions_test.go
  internal/provider/provider.go
  templates/data-sources/locations_regions.md.tmpl
Labels: new feature

#273 #202: Datasource packetfabric_locations_markets
  docs/data-sources/packetfabric_locations_markets.md
  examples/data-sources/packetfabric_locations_markets/data-source.tf
  internal/packetfabric/location_market.go
  internal/provider/datasource_locations_markets.go
  internal/provider/datasource_locations_markets_test.go
  internal/provider/provider.go
  templates/data-sources/locations_markets.md.tmpl
Labels: new feature

#279 #207: Datasource packetfabric_port_vlans
  docs/data-sources/packetfabric_port_vlans.md
  examples/data-sources/packetfabric_cs_aws_hosted_connection/data-source.tf
  examples/data-sources/packetfabric_cs_azure_hosted_connection/data-source.tf
  examples/data-sources/packetfabric_cs_dedicated_connections/data-source.tf
  examples/data-sources/packetfabric_cs_google_hosted_connection/data-source.tf
  examples/data-sources/packetfabric_cs_oracle_hosted_connection/data-source.tf
  examples/data-sources/packetfabric_link_aggregation_group/data-source.tf
  examples/data-sources/packetfabric_port/data-source.tf
  examples/data-sources/packetfabric_port_vlans/data-source.tf
  internal/packetfabric/interfaces.go
  internal/provider/datasource_port_vlan_summary.go
  internal/provider/datasource_port_vlan_summary_test.go
  internal/provider/provider.go
  internal/testutil/testutil.go
  templates/data-sources/port_vlans.md.tmpl
Labels: new feature

#281 #205: Resource packetfabric_port_loa
  docs/resources/packetfabric_port_loa.md
  examples/main.tf
  examples/resources/packetfabric_port_loa/resource.tf
  internal/packetfabric/interfaces.go
  internal/provider/provider.go
  internal/provider/resource_port_loa.go
  internal/provider/resource_port_loa_test.go
  templates/resources/port_loa.md.tmpl
Labels: new feature

#285 Add import for IBM hosted cloud
  docs/data-sources/packetfabric_port_vlans.md
  docs/resources/packetfabric_cs_ibm_hosted_connection.md
  examples/main.tf
  examples/use-cases/backbone_virtual_circuit/main.tf
  templates/data-sources/locations_port_availability.md.tmpl
  templates/data-sources/port_vlans.md.tmpl
  templates/resources/cs_ibm_hosted_connection.md.tmpl
Labels: documentation

#280 #210: Datasource packetfabric_port_device_info
  docs/data-sources/packetfabric_port_device_info.md
  examples/data-sources/packetfabric_port_device_info/data-source.tf
  internal/packetfabric/interfaces.go
  internal/provider/datasource_port_device_info.go
  internal/provider/datasource_port_device_info_test.go
  internal/provider/provider.go
  templates/data-sources/port_device_info.md.tmpl
Labels: new feature

#286 Updating the getting started page with video and data source links
  docs/guides/getting_started.md
  templates/guides/getting_started.md
Labels: documentation

#288 Fixed formatting error in data source links
  docs/guides/getting_started.md
  templates/guides/getting_started.md
Labels: documentation

#270 #200: Datasource packetfabric_locations_cloud
  docs/data-sources/packetfabric_cs_aws_hosted_connection.md
  docs/data-sources/packetfabric_cs_azure_hosted_connection.md
  docs/data-sources/packetfabric_cs_dedicated_connections.md
  docs/data-sources/packetfabric_cs_google_hosted_connection.md
  docs/data-sources/packetfabric_cs_ibm_hosted_connection.md
  docs/data-sources/packetfabric_cs_oracle_hosted_connection.md
  docs/data-sources/packetfabric_link_aggregation_group.md
  docs/data-sources/packetfabric_locations_cloud.md
  docs/data-sources/packetfabric_port.md
  docs/data-sources/packetfabric_port_device_info.md
  docs/data-sources/packetfabric_port_vlans.md
  docs/guides/getting_started.md
  docs/resources/packetfabric_cloud_router_connection_ibm.md
  docs/resources/packetfabric_cloud_router_connection_oracle.md
  docs/resources/packetfabric_cs_ibm_hosted_connection.md
  examples/data-sources/packetfabric_locations_cloud/data-source.tf
  examples/main.tf
  internal/packetfabric/cloud_locations.go
  internal/provider/datasource_cloud_locations.go
  internal/provider/datasource_cloud_locations_test.go
  internal/provider/provider.go
  templates/data-sources/locations_cloud.md.tmpl
  templates/guides/getting_started.md
  templates/guides/importing.md
Labels: new feature
