Repository PacketFabric/terraform-provider-packetfabric, pull requests merged in 2022-10, with the labels that each got.

#151 Fix #149: Remove POP and Description from READ resource READ.
  CHANGELOG.md
  examples/main.tf
  examples/provider/provider.tf
  examples/test_local.sh
  examples/use-cases/backbone_virtual_circuit/main.tf
  examples/use-cases/cloud_router_aws/main.tf
  examples/use-cases/cloud_router_google_ipsec/main.tf
  examples/use-cases/dedicated_cloud_aws/main.tf
  examples/use-cases/hosted_cloud_aws/main.tf
  examples/use-cases/hosted_cloud_azure/main.tf
  examples/use-cases/hosted_cloud_google/main.tf
  examples/use-cases/test_local.sh
  internal/provider/resource_router_connection.go
Labels: bugfix

#173 Fix/169: Change required params to optional
  internal/provider/resource_backbone.go
  internal/provider/resource_ix_vc.go
Labels: bugfix

#176 Fix failing UT.
  internal/packetfabric/cloud_service_aws_test.go
Labels: bugfix

#177 Fix/165: Fix context cancelled.
  internal/provider/resource_backbone.go
Labels: bugfix

#178 Fix/lint issues
  internal/packetfabric/bgp_session_test.go
  internal/packetfabric/cloud_router_test.go
  internal/packetfabric/cloud_service.go
  internal/packetfabric/cloud_service_azure.go
  internal/packetfabric/interfaces.go
  internal/packetfabric/service_status_check.go
  internal/provider/resource_aws_cloud_router_connection.go
  internal/provider/resource_cloud_router.go
  internal/provider/resource_cloud_service.go
  internal/provider/resource_google_cloud_router_connection.go
  internal/provider/resource_ibm_route_cloud_connection.go
  internal/provider/resource_ipsec_route_cloud_connection.go
  internal/provider/resource_oracle_route_cloud_connection.go
Labels: enhancement

#182 Fix Prefixes attribute missing from resource.
  internal/packetfabric/bgp_session.go
  internal/provider/resource_bgp_session.go
Labels: bugfix

#184 Fix/158: Fix published_quote_line_uuid attribute missing on resourceRouterConnectionAWS
  internal/provider/resource_aws_cloud_router_connection.go
Labels: bugfix

#183 Fix/160: Fix Backbone Virtual Circuit speed burst
  internal/provider/resource_add_speed_burst.go
Labels: bugfix

#174 #164: Fix incorrect naming in the code.
  internal/packetfabric/cloud_service.go
  internal/packetfabric/cloud_service_aws_test.go
  internal/packetfabric/vc_backbone.go
  internal/packetfabric/vc_backbone_test.go
  internal/provider/provider.go
  internal/provider/resource_vc_backbone.go
Labels: enhancement, bugfix

#180 Fix/159: Fix Port Cloud Router connection update and delete.
  internal/packetfabric/cloud_router_connection.go
  internal/packetfabric/cloud_router_connection_test.go
  internal/provider/resource_aws_cloud_router_connection.go
  internal/provider/resource_azure_cloud_router_connection.go
  internal/provider/resource_cloud_router.go
  internal/provider/resource_google_cloud_router_connection.go
  internal/provider/resource_ibm_route_cloud_connection.go
  internal/provider/resource_oracle_route_cloud_connection.go
  internal/provider/resource_port_cloud_router_connection.go
Labels: bugfix

#189 #181: Don't set autoneg attribute if absent.
  internal/packetfabric/interfaces.go
  internal/provider/resource_ports.go
Labels: bugfix

#186 Fix/157: Add a 20sec delay when deleting a Cloud Router Connection
  internal/packetfabric/cloud_router_connection.go
  internal/packetfabric/cloud_service_aws.go
Labels: enhancement, bugfix

#190 Fix/91: Fix Hosted Marketplace connections dele not working.
  internal/packetfabric/cloud_service_aws.go
  internal/provider/resource_aws_hosted_mkt.go
  internal/provider/resource_azure_hosted_mkt_conn.go
  internal/provider/resource_google_hosted_mkt_conn.go
  internal/provider/resource_oracle_mkt_cloud_conn.go
Labels: bugfix

#195 #161: Fix resource_backbone_virtual_circuit_marketplace.
  internal/packetfabric/cloud_service.go
  internal/provider/resource_aws_hosted_mkt.go
  internal/provider/resource_azure_hosted_mkt_conn.go
  internal/provider/resource_backbone.go
  internal/provider/resource_google_hosted_mkt_conn.go
  internal/provider/resource_ix_vc.go
  internal/provider/resource_oracle_mkt_cloud_conn.go
  internal/provider/resource_third_party_virtual_circuit.go
Labels: bugfix

#217 Enable gofmt check in lint and fix for 163
  .golangci.yml
  internal/provider/datasource_backbone_services.go
  internal/provider/datasource_cloud_conn.go
  internal/provider/provider.go
  internal/provider/resource_azure_req_express_dedicated_conn.go
  internal/provider/resource_bgp_prefixes.go
  internal/provider/resource_point_to_point.go
Labels: bugfix

#215 Fix/172: Wait till packetfabric_backbone_virtual_circuit is active.
  internal/packetfabric/vc_backbone.go
  internal/provider/resource_backbone.go
Labels: bugfix

#216 Fix/192: packetfabric_cloud_router_connection_ipsec: accept empty value for phase2_authentication_algo
  internal/provider/resource_ipsec_route_cloud_connection.go
Labels: bugfix

#218 Fix/171: Wait till packetfabric_point_to_point is active.
  internal/packetfabric/point_to_point.go
  internal/provider/resource_point_to_point.go
Labels: bugfix

#187 Fix/156: Fix plugin crash due to schema error
  internal/provider/datasource_backbone_services.go
  internal/provider/provider.go
Labels: bugfix

#221 Fix/219: FIx datasource packetfabric_marketplace_service_request.
  internal/packetfabric/cloud_service.go
  internal/provider/datasource_vc_requests.go
Labels: bugfix

#220 Fix/169: Fix bandwidth schema Optional/Required
  internal/provider/resource_backbone.go
  internal/provider/resource_third_party_virtual_circuit.go
Labels: bugfix

#222 Fix invalid required fields for packetfabric_ix_virtual_circuit_marketplace with longhaul_type
  internal/provider/resource_backbone.go
  internal/provider/resource_ix_vc.go
  internal/provider/resource_third_party_virtual_circuit.go
Labels: bugfix

#168 Acceptance Tests v0.3.2
  Makefile
  README.md
  internal/packetfabric/locations.go
  internal/provider/provider_test.go
  internal/provider/resource_cloud_router_test.go
  internal/provider/resource_ix_vc_test.go
  internal/provider/resource_point_to_point_test.go
  internal/provider/resource_port_test.go
  internal/provider/resource_third_party_virtual_circuit_test.go
  internal/testutil/testutil.go
Labels: new feature
