Repository PacketFabric/terraform-provider-packetfabric, pull requests merged in 2022-08, with the labels that each got.

#79 Fix #70: Change cloud service delete URI
  internal/packetfabric/cloud_service.go
  internal/provider/resource_google_request_hosted_conn.go
Labels: bugfix

#78 Fix #66: Remove warning
  internal/provider/resource_outbound_cross_connect.go
Labels: enhancement, release_v0.2.0

#80 Fix #64: Change azure components
  internal/packetfabric/cloud_service_azure.go
Labels: bugfix

#81 Fix #54: Omit src_svlan when not being parsed
  internal/packetfabric/cloud_service_aws.go
Labels: bugfix

#73 Adding new use case examples for v0.2.0
  examples/use-cases/backbone_virtual_circuit/README.md
  examples/use-cases/backbone_virtual_circuit/main.tf
  examples/use-cases/backbone_virtual_circuit/variables.tf
  examples/use-cases/cloud_router_aws/README.md
  examples/use-cases/cloud_router_aws/main.tf
  examples/use-cases/cloud_router_aws/variables.tf
  examples/use-cases/dedicated_cloud_aws/README.md
  examples/use-cases/dedicated_cloud_aws/main.tf
  examples/use-cases/dedicated_cloud_aws/variables.tf
  examples/use-cases/hosted_cloud_aws/README.md
  examples/use-cases/hosted_cloud_aws/main.tf
  examples/use-cases/hosted_cloud_aws/secret.tfvars.sample
  examples/use-cases/hosted_cloud_aws/variables.tf
  examples/use-cases/hosted_cloud_azure/README.md
  examples/use-cases/hosted_cloud_azure/main.tf
  examples/use-cases/hosted_cloud_azure/secret.tfvars.sample
  examples/use-cases/hosted_cloud_azure/variables.tf
  examples/use-cases/hosted_cloud_google/README.md
  examples/use-cases/hosted_cloud_google/main.tf
  examples/use-cases/hosted_cloud_google/secret.tfvars.sample
  examples/use-cases/hosted_cloud_google/variables.tf
Labels: documentation, new_feature, release_v0.2.0

#96 Fix issue #92: Add Azure vlans.
  internal/packetfabric/cloud_service_aws.go
  internal/provider/resource_azure_provision_mkt.go
  internal/provider/resource_provision_mkt.go
Labels: bugfix

#94 Fix issue #83: Fix delete for Google/Aws/Azure services.
  internal/packetfabric/cloud_service_aws.go
  internal/provider/resource_backbone.go
Labels: bugfix

#95 Fix issue #90: Added missing field.
  internal/packetfabric/cloud_service_aws.go
  internal/provider/resource_aws_hosted_mkt.go
Labels: bugfix

#101 Fix issue #83: Fix Aws/Azure/Google resources delete.
  internal/packetfabric/cloud_service.go
  internal/packetfabric/cloud_service_aws.go
  internal/packetfabric/cloud_service_aws_test.go
  internal/packetfabric/cloud_service_azure.go
  internal/packetfabric/cloud_service_google.go
  internal/provider/resource_aws_request_dedicated_conn.go
  internal/provider/resource_aws_request_hosted_conn.go
  internal/provider/resource_azure_provision_mkt.go
  internal/provider/resource_azure_req_express_conn.go
  internal/provider/resource_azure_req_express_dedicated_conn.go
  internal/provider/resource_backbone.go
  internal/provider/resource_google_dedicated_conn.go
  internal/provider/resource_google_provision_mkt.go
  internal/provider/resource_google_request_hosted_conn.go
  internal/provider/resource_provision_mkt.go
Labels: bugfix, release_v0.2.1

#103 Fix #89: Delete hosted cloud services.
  internal/packetfabric/cloud_service_aws.go
  internal/provider/resource_azure_req_express_conn.go
  internal/provider/resource_google_request_hosted_conn.go
Labels: bugfix

#104 Fix parsing Azure components fields.
  internal/packetfabric/cloud_service_aws.go
Labels: bugfix

#82 Fix #58: Run make tests functional.
  internal/provider/resource_bgp_session.go
  tools/tools.go
Labels: bugfix, release_v0.2.0

#99 Fix issue-93 packetfabric_link_aggregation_group
  internal/packetfabric/link_aggregration_groups.go
  internal/provider/datasource_link_aggregation_groups.go
  internal/provider/resource_link_aggregation_groups.go
Labels: bugfix, release_v0.2.1

#117 Fix #102: Remove disable port before deletion.
  internal/provider/resource_interfaces.go
Labels: bugfix

#118 Fix/111: Add 30s delay at port creation/deletion.
  internal/provider/resource_interfaces.go
Labels: enhancement, bugfix

#119 Fix #108: RandomAlphaNumeric and CryptoRandomAlphaNumeric are not as …
  go.mod
  go.sum
Labels: bugfix

#113 Partial changes for docs update. Doesn't include changes to .go files
  docs/resources/packetfabric_aws_cloud_router_connection.md
  docs/resources/packetfabric_backbone_virtual_circuit.md
  docs/resources/packetfabric_cloud_router.md
  docs/resources/packetfabric_cloud_router_bgp_prefixes.md
  docs/resources/packetfabric_cloud_router_bgp_session.md
  docs/resources/packetfabric_cs_aws_dedicated_connection.md
  docs/resources/packetfabric_cs_aws_hosted_connection.md
  docs/resources/packetfabric_cs_aws_hosted_marketplace_connection.md
  docs/resources/packetfabric_cs_aws_provision_marketplace.md
  docs/resources/packetfabric_cs_azure_dedicated_connection.md
  docs/resources/packetfabric_cs_azure_hosted_connection.md
  docs/resources/packetfabric_cs_azure_hosted_marketplace_connection.md
  docs/resources/packetfabric_cs_azure_provision_marketplace.md
  docs/resources/packetfabric_cs_google_dedicated_connection.md
  docs/resources/packetfabric_cs_google_hosted_connection.md
  docs/resources/packetfabric_cs_google_hosted_marketplace_connection.md
  docs/resources/packetfabric_cs_google_provision_marketplace.md
  docs/resources/packetfabric_link_aggregation_group.md
  docs/resources/packetfabric_outbound_cross_connect.md
  docs/resources/packetfabric_port.md
  templates/resources/aws_cloud_router_connection.md.tmpl
  templates/resources/backbone_virtual_circuit.md.tmpl
  templates/resources/cloud_router.md.tmpl
  templates/resources/cloud_router_bgp_prefixes.md.tmpl
  templates/resources/cloud_router_bgp_session.md.tmpl
  templates/resources/cs_aws_dedicated_connection.md.tmpl
  templates/resources/cs_aws_hosted_connection.md.tmpl
  templates/resources/cs_aws_hosted_marketplace_connection.md.tmpl
  templates/resources/cs_aws_provision_marketplace.md.tmpl
  templates/resources/cs_azure_dedicated_connection.md.tmpl
  templates/resources/cs_azure_hosted_connection.md.tmpl
  templates/resources/cs_azure_hosted_marketplace_connection.md.tmpl
  templates/resources/cs_azure_provision_marketplace.md.tmpl
  templates/resources/cs_google_dedicated_connection.md.tmpl
  templates/resources/cs_google_hosted_connection.md.tmpl
  templates/resources/cs_google_hosted_marketplace_connection.md.tmpl
  templates/resources/cs_google_provision_marketplace.md.tmpl
  templates/resources/link_aggregation_group.md.tmpl
  templates/resources/outbound_cross_connect.md.tmpl
  templates/resources/packetfabric_aws_cloud_router_connection.md.tmpl
  templates/resources/packetfabric_backbone_virtual_circuit.md.tmpl
  templates/resources/packetfabric_cloud_router.md.tmpl
  templates/resources/packetfabric_cloud_router_bgp_prefixes.md.tmpl
  templates/resources/packetfabric_cloud_router_bgp_session.md.tmpl
  templates/resources/packetfabric_cs_aws_dedicated_connection.md.tmpl
  templates/resources/packetfabric_cs_aws_hosted_connection.md.tmpl
  templates/resources/packetfabric_cs_aws_hosted_marketplace_connection.md.tmpl
  templates/resources/packetfabric_cs_aws_provision_marketplace.md.tmpl
  templates/resources/packetfabric_cs_azure_dedicated_connection.md.tmpl
  templates/resources/packetfabric_cs_azure_hosted_connection.md.tmpl
  templates/resources/packetfabric_cs_azure_hosted_marketplace_connection.md.tmpl
  templates/resources/packetfabric_cs_azure_provision_marketplace.md.tmpl
  templates/resources/packetfabric_cs_google_dedicated_connection.md.tmpl
  templates/resources/packetfabric_cs_google_hosted_connection.md.tmpl
  templates/resources/packetfabric_cs_google_hosted_marketplace_connection.md.tmpl
  templates/resources/packetfabric_cs_google_provision_marketplace.md.tmpl
  templates/resources/packetfabric_link_aggregation_group.md.tmpl
  templates/resources/packetfabric_outbound_cross_connect.md.tmpl
  templates/resources/packetfabric_port.md.tmpl
  templates/resources/port.md.tmpl
Labels: documentation, release_v0.2.2

#114 Attempting to merge changes in .go files
  internal/provider/resource_aws_hosted_mkt.go
  internal/provider/resource_aws_provision_mkt.go
  internal/provider/resource_aws_request_dedicated_conn.go
  internal/provider/resource_aws_request_hosted_conn.go
  internal/provider/resource_azure_hosted_mkt_conn.go
  internal/provider/resource_azure_req_express_conn.go
  internal/provider/resource_azure_req_express_dedicated_conn.go
  internal/provider/resource_backbone.go
  internal/provider/resource_bgp_refixes.go
  internal/provider/resource_bgp_session.go
  internal/provider/resource_cloud_router.go
  internal/provider/resource_google_dedicated_conn.go
  internal/provider/resource_google_hosted_mkt_conn.go
  internal/provider/resource_google_request_hosted_conn.go
  internal/provider/resource_interfaces.go
  internal/provider/resource_link_aggregation_groups.go
  internal/provider/resource_outbound_cross_connect.go
  internal/provider/resource_provision_mkt.go
  internal/provider/resource_router_connection.go
Labels: documentation, release_v0.2.2

#121 Update examples and use cases
  .gitignore
  examples/README.md
  examples/cloud_router_aws_conn.tf
  examples/data-sources/packetfabric_azr_cloud_router_connection/data-source.tf
  examples/data-sources/packetfabric_cs_aws_hosted_marketplace_connection/data-source.tf
  examples/data-sources/packetfabric_cs_azure_hosted_marketplace_connection/data-source.tf
  examples/data-sources/packetfabric_cs_google_hosted_marketplace_connection/data-source.tf
  examples/data-sources/packetfabric_gcp_cloud_router_connection/data-source.tf
  examples/env_vars_source.sh
  examples/env_vars_source.sh.sample
  examples/env_vars_source_private.sh
  examples/main.tf
  examples/main_aws.tf
  examples/resources/packetfabric_cloud_services_aws_req_hosted_conn/resource.tf
  examples/secret.tfvars.sample
  examples/use-cases/backbone_virtual_circuit/README.md
  examples/use-cases/backbone_virtual_circuit/main.tf
  examples/use-cases/backbone_virtual_circuit/secret.tfvars.sample
  examples/use-cases/backbone_virtual_circuit/variables.tf
  examples/use-cases/cloud_router_aws/README.md
  examples/use-cases/cloud_router_aws/secret.tfvars.sample
  examples/use-cases/dedicated_cloud_aws/README.md
  examples/use-cases/dedicated_cloud_aws/main.tf
  examples/use-cases/dedicated_cloud_aws/secret.tfvars.sample
  examples/use-cases/hosted_cloud_aws/README.md
  examples/use-cases/hosted_cloud_azure/README.md
  examples/use-cases/hosted_cloud_azure/secret.tfvars.sample
  examples/use-cases/hosted_cloud_google/README.md
  examples/use-cases/hosted_cloud_google/secret.tfvars.sample
  examples/variables.tf
Labels: documentation, release_v0.2.2

#122 Updates all examples resources and data sources
  examples/data-sources/packetfabric_activitylog/data-source.tf
  examples/data-sources/packetfabric_aws_cloud_router_connection/data-source.tf
  examples/data-sources/packetfabric_billing/data-source.tf
  examples/data-sources/packetfabric_cloud_router/data-source.tf
  examples/data-sources/packetfabric_cloud_router_bgp_prefixes/data-source.tf
  examples/data-sources/packetfabric_cloud_router_bgp_session/data-source.tf
  examples/data-sources/packetfabric_cs_aws_dedicated_connection_conn/data-source.tf
  examples/data-sources/packetfabric_cs_aws_hosted_connection/data-source.tf
  examples/data-sources/packetfabric_cs_azure_dedicated_connection/data-source.tf
  examples/data-sources/packetfabric_cs_azure_hosted_connection/data-source.tf
  examples/data-sources/packetfabric_cs_google_dedicated_connection/data-source.tf
  examples/data-sources/packetfabric_cs_google_hosted_connection/data-source.tf
  examples/data-sources/packetfabric_link_aggregation_group/data-source.tf
  examples/data-sources/packetfabric_locations/data-source.tf
  examples/data-sources/packetfabric_outbound_cross_connect/data-source.tf
  examples/data-sources/packetfabric_port/data-source.tf
  examples/env_vars_source.sh.sample
  examples/main.tf
  examples/provider/provider.tf
  examples/resources/packetfabric_aws_cloud_router_connection/resource.tf
  examples/resources/packetfabric_backbone_virtual_circuit/resource.tf
  examples/resources/packetfabric_cloud_router/resource.tf
  examples/resources/packetfabric_cloud_router_bgp_prefixes/resource.tf
  examples/resources/packetfabric_cloud_router_bgp_session/resource.tf
  examples/resources/packetfabric_cs_aws_dedicated_connection/resource.tf
  examples/resources/packetfabric_cs_aws_hosted_connection/resource.tf
  examples/resources/packetfabric_cs_aws_hosted_marketplace_connection/resource.tf
  examples/resources/packetfabric_cs_aws_provision_marketplace/resource.tf
  examples/resources/packetfabric_cs_azure_dedicated_connection/resource.tf
  examples/resources/packetfabric_cs_azure_hosted_connection/resource.tf
  examples/resources/packetfabric_cs_azure_hosted_marketplace_connection/resource.tf
  examples/resources/packetfabric_cs_azure_provision_marketplace/resource.tf
  examples/resources/packetfabric_cs_google_dedicated_connection/resource.tf
  examples/resources/packetfabric_cs_google_hosted_connection/resource.tf
  examples/resources/packetfabric_cs_google_hosted_marketplace_connection/resource.tf
  examples/resources/packetfabric_cs_google_provision_marketplace/resource.tf
  examples/resources/packetfabric_link_aggregation_group/resource.tf
  examples/resources/packetfabric_outbound_cross_connect/resource.tf
  examples/resources/packetfabric_port/resource.tf
  examples/use-cases/backbone_virtual_circuit/main.tf
  examples/use-cases/cloud_router_aws/main.tf
  examples/use-cases/cloud_router_aws/variables.tf
  examples/use-cases/dedicated_cloud_aws/main.tf
  examples/use-cases/dedicated_cloud_aws/variables.tf
  examples/use-cases/hosted_cloud_aws/main.tf
  examples/use-cases/hosted_cloud_aws/variables.tf
  examples/use-cases/hosted_cloud_google/main.tf
  examples/variables.tf
Labels: documentation, release_v0.2.2
