Repository PacketFabric/terraform-provider-packetfabric, pull requests merged in 2023-03, with the labels that each got.

#364 Update untagged, fix warning and cleanup
  docs/resources/packetfabric_backbone_virtual_circuit.md
  internal/packetfabric/cloud_service_aws.go
  internal/packetfabric/services.go
  internal/provider/resource_backbone.go
  internal/provider/resource_ix_vc.go
  internal/provider/resource_third_party_virtual_circuit.go
  templates/resources/backbone_virtual_circuit.md.tmpl
Labels: bug, enhancement

#361 Update lag information on get resource for import
  .gitignore
  docs/resources/packetfabric_link_aggregation_group.md
  internal/provider/resource_link_aggregation_groups.go
  templates/resources/link_aggregation_group.md.tmpl
Labels: enhancement

#366 Fix autoneg and add port status in packetfabric_port
  docs/resources/packetfabric_link_aggregation_group.md
  docs/resources/packetfabric_port.md
  internal/packetfabric/ports.go
  internal/provider/resource_port.go
Labels: enhancement, bugfix

#362 Update default tf version to 1.1.0 in all examples
  docs/index.md
  examples/provider/provider.tf
  examples/test.tf
  examples/use-cases/backbone_virtual_circuit/main.tf
  examples/use-cases/backbone_virtual_circuit_mesh/main.tf
  examples/use-cases/cloud_router_aws/provider.tf
  examples/use-cases/cloud_router_aws_google/provider.tf
  examples/use-cases/cloud_router_google_azure/provider.tf
  examples/use-cases/cloud_router_google_ipsec/provider.tf
  examples/use-cases/cloud_router_ibm_oracle/provider.tf
  examples/use-cases/cloud_router_module/main.tf
  examples/use-cases/cloud_router_module/modules/packetfabric/cloud_router.tf
  examples/use-cases/dedicated_cloud_aws/main.tf
  examples/use-cases/flex_bandwidth/main.tf
  examples/use-cases/hosted_cloud_aws/main.tf
  examples/use-cases/hosted_cloud_azure/main.tf
  examples/use-cases/hosted_cloud_google/main.tf
  examples/use-cases/marketplace/a_side/main.tf
  examples/use-cases/marketplace/z_side/main.tf
Labels: documentation

#363 Creating test_hcls.go, updating schemas and envars.
  internal/testutil/test_envar_keys.go
  internal/testutil/test_hcls.go
  internal/testutil/test_schemas.go
  internal/testutil/testutil.go
Labels: acceptance test

#373 Update Azure Dedicated Cloud status check
  internal/provider/resource_azure_dedicated_conn.go
Labels: enhancement

#374 Add PO Number to resources
  docs/resources/packetfabric_backbone_virtual_circuit.md
  docs/resources/packetfabric_cloud_router.md
  docs/resources/packetfabric_cloud_router_connection_aws.md
  docs/resources/packetfabric_cloud_router_connection_azure.md
  docs/resources/packetfabric_cloud_router_connection_google.md
  docs/resources/packetfabric_cloud_router_connection_ibm.md
  docs/resources/packetfabric_cloud_router_connection_ipsec.md
  docs/resources/packetfabric_cloud_router_connection_oracle.md
  docs/resources/packetfabric_cloud_router_connection_port.md
  docs/resources/packetfabric_cs_aws_dedicated_connection.md
  docs/resources/packetfabric_cs_aws_hosted_connection.md
  docs/resources/packetfabric_cs_azure_dedicated_connection.md
  docs/resources/packetfabric_cs_azure_hosted_connection.md
  docs/resources/packetfabric_cs_google_dedicated_connection.md
  docs/resources/packetfabric_cs_google_hosted_connection.md
  docs/resources/packetfabric_cs_ibm_hosted_connection.md
  docs/resources/packetfabric_cs_oracle_hosted_connection.md
  docs/resources/packetfabric_link_aggregation_group.md
  docs/resources/packetfabric_point_to_point.md
  docs/resources/packetfabric_port.md
  internal/packetfabric/cloud_router.go
  internal/packetfabric/cloud_router_connection.go
  internal/packetfabric/cloud_router_connection_test.go
  internal/packetfabric/cloud_router_port.go
  internal/packetfabric/cloud_service_aws.go
  internal/packetfabric/cloud_service_aws_test.go
  internal/packetfabric/cloud_service_azure.go
  internal/packetfabric/cloud_service_google.go
  internal/packetfabric/cloud_service_ibm.go
  internal/packetfabric/cloud_service_oracle.go
  internal/packetfabric/point_to_point.go
  internal/packetfabric/ports.go
  internal/packetfabric/services.go
  internal/provider/resource_aws_cloud_router_connection.go
  internal/provider/resource_aws_dedicated_conn.go
  internal/provider/resource_aws_hosted_conn.go
  internal/provider/resource_azure_cloud_router_connection.go
  internal/provider/resource_azure_dedicated_conn.go
  internal/provider/resource_azure_hosted_conn.go
  internal/provider/resource_backbone.go
  internal/provider/resource_cloud_router.go
  internal/provider/resource_cloud_router_connection_common.go
  internal/provider/resource_cloud_service_common.go
  internal/provider/resource_google_cloud_router_connection.go
  internal/provider/resource_google_dedicated_conn.go
  internal/provider/resource_google_hosted_conn.go
  internal/provider/resource_ibm_hosted_conn.go
  internal/provider/resource_ibm_route_cloud_connection.go
  internal/provider/resource_ipsec_route_cloud_connection.go
  internal/provider/resource_link_aggregation_groups.go
  internal/provider/resource_oracle_cloud_router_connection.go
  internal/provider/resource_oracle_hosted_conn.go
  internal/provider/resource_point_to_point.go
  internal/provider/resource_port.go
  internal/provider/resource_port_cloud_router_connection.go
Labels: new feature

#377 Update maybe_nat and maybe_dnat in all packetfabric_cloud_router_connection resources
  docs/resources/packetfabric_cloud_router_connection_aws.md
  docs/resources/packetfabric_cloud_router_connection_google.md
  docs/resources/packetfabric_cloud_router_connection_ibm.md
  docs/resources/packetfabric_cloud_router_connection_oracle.md
  docs/resources/packetfabric_cloud_router_connection_port.md
  internal/provider/resource_aws_cloud_router_connection.go
  internal/provider/resource_azure_cloud_router_connection.go
  internal/provider/resource_google_cloud_router_connection.go
  internal/provider/resource_ibm_route_cloud_connection.go
  internal/provider/resource_oracle_cloud_router_connection.go
  internal/provider/resource_port_cloud_router_connection.go
Labels: bugfix

#375 Add Object Labels to resources
  docs/resources/packetfabric_backbone_virtual_circuit.md
  docs/resources/packetfabric_cloud_router.md
  docs/resources/packetfabric_cloud_router_connection_aws.md
  docs/resources/packetfabric_cloud_router_connection_azure.md
  docs/resources/packetfabric_cloud_router_connection_google.md
  docs/resources/packetfabric_cloud_router_connection_ibm.md
  docs/resources/packetfabric_cloud_router_connection_ipsec.md
  docs/resources/packetfabric_cloud_router_connection_oracle.md
  docs/resources/packetfabric_cloud_router_connection_port.md
  docs/resources/packetfabric_cloud_router_quick_connect.md
  docs/resources/packetfabric_cs_aws_dedicated_connection.md
  docs/resources/packetfabric_cs_aws_hosted_connection.md
  docs/resources/packetfabric_cs_azure_dedicated_connection.md
  docs/resources/packetfabric_cs_azure_hosted_connection.md
  docs/resources/packetfabric_cs_google_dedicated_connection.md
  docs/resources/packetfabric_cs_google_hosted_connection.md
  docs/resources/packetfabric_cs_ibm_hosted_connection.md
  docs/resources/packetfabric_cs_oracle_hosted_connection.md
  docs/resources/packetfabric_link_aggregation_group.md
  docs/resources/packetfabric_point_to_point.md
  docs/resources/packetfabric_port.md
  examples/resources/packetfabric_cloud_router/resource.tf
  examples/resources/packetfabric_cloud_router_connection_aws/resource.tf
  examples/resources/packetfabric_port/resource.tf
  internal/packetfabric/labels.go
  internal/provider/labels_common.go
  internal/provider/resource_aws_cloud_router_connection.go
  internal/provider/resource_aws_dedicated_conn.go
  internal/provider/resource_aws_hosted_conn.go
  internal/provider/resource_azure_cloud_router_connection.go
  internal/provider/resource_azure_dedicated_conn.go
  internal/provider/resource_azure_hosted_conn.go
  internal/provider/resource_backbone.go
  internal/provider/resource_cloud_router.go
  internal/provider/resource_cloud_router_connection_common.go
  internal/provider/resource_cloud_router_quick_connect.go
  internal/provider/resource_cloud_service_common.go
  internal/provider/resource_google_cloud_router_connection.go
  internal/provider/resource_google_dedicated_conn.go
  internal/provider/resource_google_hosted_conn.go
  internal/provider/resource_ibm_hosted_conn.go
  internal/provider/resource_ibm_route_cloud_connection.go
  internal/provider/resource_ipsec_route_cloud_connection.go
  internal/provider/resource_link_aggregation_groups.go
  internal/provider/resource_oracle_cloud_router_connection.go
  internal/provider/resource_oracle_hosted_conn.go
  internal/provider/resource_point_to_point.go
  internal/provider/resource_port.go
  internal/provider/resource_port_cloud_router_connection.go
  templates/guides/labels.md
Labels: new feature

#380 Set omitempty on po_number where missing
  internal/packetfabric/cloud_router_connection.go
  internal/packetfabric/point_to_point.go
  internal/packetfabric/ports.go
Labels: bugfix

#381 Update Oracle Cloud Router Connect API endpoint from v2 to v2.1
  internal/packetfabric/cloud_router_connection.go
Labels: enhancement

#379 Fix update issue with autoneg in packetfabric_port interfaces 10Gbps
  internal/packetfabric/ports.go
  internal/provider/resource_cloud_service_common.go
  internal/provider/resource_link_aggregation_groups.go
  internal/provider/resource_port.go
Labels: bugfix

#382 Update autoneg in use case examples
  examples/use-cases/backbone_virtual_circuit/variables.tf
  examples/use-cases/cloud_router_aws_oracle_port/port.tf
  examples/use-cases/cloud_router_aws_oracle_port/variables_port.tf
  examples/use-cases/flex_bandwidth/main.tf
  examples/use-cases/flex_bandwidth/variables.tf
  examples/use-cases/hosted_cloud_aws/variables.tf
  examples/use-cases/hosted_cloud_azure/variables.tf
  examples/use-cases/hosted_cloud_google/variables.tf
  examples/use-cases/hosted_cloud_ibm/variables.tf
Labels: documentation

#383 Update default value for port autoneg
  docs/resources/packetfabric_port.md
  internal/provider/resource_port.go
Labels: documentation

#384 Update bgp_state in cloud router connection and BGP session data-sources
  docs/data-sources/packetfabric_cloud_router_bgp_session.md
  docs/data-sources/packetfabric_cloud_router_connections.md
  docs/guides/importing.md
  internal/packetfabric/bgp_session.go
  internal/packetfabric/cloud_router_connection.go
  internal/packetfabric/cloud_router_connection_test.go
  internal/provider/datasource_bgp_session.go
  internal/provider/datasource_cloud_conn.go
  internal/provider/resource_aws_cloud_router_connection.go
  internal/provider/resource_azure_cloud_router_connection.go
  internal/provider/resource_google_cloud_router_connection.go
  internal/provider/resource_ibm_route_cloud_connection.go
  internal/provider/resource_oracle_cloud_router_connection.go
  internal/provider/resource_port_cloud_router_connection.go
  templates/guides/labels.md
Labels: enhancement

#390 Increase status check interval in Cloud Router, Cloud Services, Backbone VC, PTP, Port
  docs/resources/packetfabric_cloud_router_bgp_session.md
  internal/packetfabric/cloud_router_connection.go
  internal/packetfabric/cloud_service_aws.go
  internal/packetfabric/service_status_check.go
  internal/provider/resource_add_speed_burst.go
  internal/provider/resource_aws_dedicated_conn.go
  internal/provider/resource_aws_hosted_conn.go
  internal/provider/resource_azure_dedicated_conn.go
  internal/provider/resource_azure_hosted_conn.go
  internal/provider/resource_backbone.go
  internal/provider/resource_bgp_session.go
  internal/provider/resource_google_dedicated_conn.go
  internal/provider/resource_google_hosted_conn.go
  internal/provider/resource_ibm_hosted_conn.go
  internal/provider/resource_oracle_hosted_conn.go
  internal/provider/resource_point_to_point.go
  internal/provider/resource_port.go
  internal/provider/resource_third_party_virtual_circuit.go
Labels: enhancement

#394 Add back importing page
  docs/guides/importing.md
  templates/guides/importing.md
Labels: documentation

#393 Add validation on BGP prefix in/ou in BGP session resource
  internal/provider/resource_bgp_session.go
Labels: enhancement

#397 Handling svlan unset creating config diff with terraform plan after VC creation
  docs/resources/packetfabric_backbone_virtual_circuit.md
  internal/provider/resource_aws_hosted_conn.go
  internal/provider/resource_azure_hosted_conn.go
  internal/provider/resource_backbone.go
  internal/provider/resource_google_hosted_conn.go
  internal/provider/resource_ibm_hosted_conn.go
  internal/provider/resource_ix_vc.go
  internal/provider/resource_port_cloud_router_connection.go
  internal/provider/resource_third_party_virtual_circuit.go
Labels: bugfix

#376 New packetfabric_cloud_provider_credential resources
  docs/resources/packetfabric_cloud_provider_credential_aws.md
  docs/resources/packetfabric_cloud_provider_credential_google.md
  examples/resources/packetfabric_cloud_provider_credential_aws/resource.tf
  examples/resources/packetfabric_cloud_provider_credential_google/resource.tf
  examples/test.tf
  internal/packetfabric/cloud_provider_credential.go
  internal/provider/provider.go
  internal/provider/resource_aws_cloud_provider_credential.go
  internal/provider/resource_google_cloud_provider_credential.go
  templates/resources/cloud_provider_credential_aws.md.tmpl
  templates/resources/cloud_provider_credential_google.md.tmpl
Labels: new feature

#399 Correct pop set in the cloud router connection read functions
  internal/provider/resource_aws_cloud_router_connection.go
  internal/provider/resource_google_cloud_router_connection.go
  internal/provider/resource_ibm_route_cloud_connection.go
  internal/provider/resource_ipsec_route_cloud_connection.go
  internal/provider/resource_oracle_cloud_router_connection.go
Labels: bugfix

#400 PSE-11004: add cloud_router_circuit_id to cr import request
  docs/data-sources/packetfabric_quick_connect_requests.md
  internal/packetfabric/cloud_router_quick_connect.go
  internal/packetfabric/cloud_router_request.go
  internal/provider/datasource_quick_connect_requests.go
Labels: enhancement

#401 Add validation for subscription_term and longhaul_type
  internal/provider/resource_backbone.go
  internal/provider/resource_flex_bandwidth.go
  internal/provider/resource_port.go
Labels: enhancement

#386 Update BGP Session resource read to set all fields
  CONTRIBUTING.md
  docs/resources/packetfabric_cloud_router_bgp_session.md
  internal/packetfabric/bgp_session.go
  internal/provider/resource_bgp_session.go
Labels: enhancement

#408 Update AWS Hosted Cloud resource/data-source adding cloud side provisioning option
  docs/data-sources/packetfabric_cs_aws_hosted_connection.md
  docs/data-sources/packetfabric_cs_azure_hosted_connection.md
  docs/data-sources/packetfabric_cs_google_hosted_connection.md
  docs/data-sources/packetfabric_cs_oracle_hosted_connection.md
  docs/resources/packetfabric_cs_aws_hosted_connection.md
  examples/resources/packetfabric_cs_aws_hosted_connection/resource.tf
  examples/test.tf
  examples/test_vars.tf
  examples/use-cases/hosted_cloud_aws/main.tf
  examples/use-cases/hosted_cloud_aws/variables.tf
  internal/packetfabric/cloud_service_aws.go
  internal/packetfabric/services.go
  internal/provider/cloud_common.go
  internal/provider/datasource_aws_hosted_service.go
  internal/provider/datasource_cloud_service_aws.go
  internal/provider/datasource_hosted_aws_google_azure_oracle_conn.go.go
  internal/provider/datasource_vc_requests.go
  internal/provider/resource_aws_hosted_conn.go
  internal/provider/resource_azure_hosted_conn.go
  internal/provider/resource_cloud_service_common.go
  internal/provider/resource_google_hosted_conn.go
  internal/provider/resource_ibm_hosted_conn.go
  internal/provider/resource_oracle_hosted_conn.go
  templates/resources/cs_aws_hosted_connection.md.tmpl
Labels: new feature
