Repository PacketFabric/terraform-provider-packetfabric, pull requests merged in 2023-02, with the labels that each got.

#320 Add FlexBandwith attribute to Backbone Virtual Circuit resource and data-source
  docs/data-sources/packetfabric_virtual_circuits.md
  docs/resources/packetfabric_backbone_virtual_circuit.md
  docs/resources/packetfabric_backbone_virtual_circuit_marketplace.md
  docs/resources/packetfabric_ix_virtual_circuit_marketplace.md
  internal/packetfabric/cloud_service.go
  internal/provider/datasource_backbone_services.go
  internal/provider/resource_backbone.go
  internal/provider/resource_ix_vc.go
  internal/provider/resource_third_party_virtual_circuit.go
Labels: enhancement

#323 Feature/248: Resource packetfabric_flex_bandwidth
  CHANGELOG.md
  CONTRIBUTING.md
  docs/data-sources/packetfabric_cloud_router_bgp_session.md
  docs/data-sources/packetfabric_port_device_info.md
  docs/index.md
  docs/resources/packetfabric_backbone_virtual_circuit.md
  docs/resources/packetfabric_cloud_router_bgp_session.md
  docs/resources/packetfabric_flex_bandwidth.md
  examples/data-sources/packetfabric_cloud_router_bgp_session/data-source.tf
  examples/provider/provider.tf
  examples/resources/packetfabric_flex_bandwidth/resource.tf
  examples/test.tf
  examples/test_vars.tf
  examples/use-cases/backbone_virtual_circuit/main.tf
  examples/use-cases/backbone_virtual_circuit_mesh/main.tf
  examples/use-cases/cloud_router_aws/provider.tf
  examples/use-cases/cloud_router_aws_google/provider.tf
  examples/use-cases/cloud_router_google_azure/provider.tf
  examples/use-cases/cloud_router_google_ipsec/provider.tf
  examples/use-cases/cloud_router_ibm_oracle/provider.tf
  examples/use-cases/cloud_router_module/main.tf
  examples/use-cases/cloud_router_module/modules/packetfabric/cloud_router.tf
  examples/use-cases/dedicated_cloud_aws/main.tf
  examples/use-cases/hosted_cloud_aws/main.tf
  examples/use-cases/hosted_cloud_azure/main.tf
  examples/use-cases/hosted_cloud_google/main.tf
  examples/use-cases/marketplace/a_side/main.tf
  examples/use-cases/marketplace/z_side/main.tf
  internal/packetfabric/flex_bandwith.go
  internal/provider/provider.go
  internal/provider/resource_backbone.go
  internal/provider/resource_flex_bandwidth.go
  templates/data-sources/marketplace_service_port_requests.md.tmpl
  templates/resources/flex_bandwidth.md.tmpl
  templates/resources/marketplace_service_port_accept_request.md.tmpl
  templates/resources/marketplace_service_port_reject_request.md.tmpl
Labels: new feature

#307 255: Feature datasource packetfabric_quick_connect_requests.
  docs/data-sources/packetfabric_quick_connect_requests.md
  examples/data-sources/packetfabric_quick_connect_requests/data-source.tf
  examples/test.tf
  internal/packetfabric/cloud_router_request.go
  internal/provider/datasource_quick_connect_requests.go
  internal/provider/provider.go
  templates/data-sources/quick_connect_requests.md.tmpl
Labels: new feature

#308 254: Implement feature packetfabric_quick_connect_reject_request.
  docs/resources/packetfabric_quick_connect_reject_request.md
  examples/resources/packetfabric_quick_connect_reject_request/resource.tf
  internal/packetfabric/cloud_service.go
  internal/provider/provider.go
  internal/provider/resource_quick_connect_reject_request.go
  templates/resources/marketplace_service_accept_port_request.md.tmpl
  templates/resources/marketplace_service_reject_port_request.md.tmpl
  templates/resources/quick_connect_reject_request.md.tmpl
Labels: new feature

#310 257: Resource packetfabric_cloud_router_quick_connect.
  docs/resources/packetfabric_cloud_router_quick_connect.md
  examples/resources/packetfabric_cloud_router_quick_connect/resource.tf
  examples/test.tf
  examples/test_vars.tf
  internal/packetfabric/cloud_router_quick_connect.go
  internal/provider/provider.go
  internal/provider/resource_cloud_router_quick_connect.go
  templates/resources/cloud_router_quick_connect.md.tmpl
Labels: new feature

#311 Feature/248: Resource packetfabric_marketplace_service
  docs/resources/packetfabric_marketplace_service.md
  examples/provider/provider.tf
  examples/resources/packetfabric_marketplace_service/resource.tf
  examples/test.tf
  examples/test_vars.tf
  internal/packetfabric/marketplace.go
  internal/provider/provider.go
  internal/provider/resource_marketplace.go
  templates/resources/marketplace_service.md.tmpl
Labels: new feature

#328 Run tfdocsplugin for v0.9
  docs/data-sources/packetfabric_quick_connect_requests.md
  docs/data-sources/packetfabric_virtual_circuits.md
  docs/index.md
  docs/resources/packetfabric_backbone_virtual_circuit.md
  docs/resources/packetfabric_flex_bandwidth.md
  templates/resources/marketplace_service_accept_port_request.md.tmpl
  templates/resources/marketplace_service_reject_port_request.md.tmpl
Labels: documentation

#331 Fix/remote address
  CHANGELOG.md
  internal/packetfabric/bgp_session.go
Labels: bugfix

#327 ACC tests base structure
  internal/testutil/test_envar_keys.go
  internal/testutil/test_schemas.go
Labels: acceptance test

#332 Add missing status check for Azure and Port Cloud Router Connection
  CHANGELOG.md
  docs/index.md
  examples/provider/provider.tf
  examples/test.tf
  examples/use-cases/backbone_virtual_circuit/main.tf
  examples/use-cases/backbone_virtual_circuit_mesh/main.tf
  examples/use-cases/cloud_router_aws/provider.tf
  examples/use-cases/cloud_router_aws_google/provider.tf
  examples/use-cases/cloud_router_google_azure/provider.tf
  examples/use-cases/cloud_router_google_ipsec/provider.tf
  examples/use-cases/cloud_router_ibm_oracle/provider.tf
  examples/use-cases/cloud_router_module/main.tf
  examples/use-cases/cloud_router_module/modules/packetfabric/cloud_router.tf
  examples/use-cases/dedicated_cloud_aws/main.tf
  examples/use-cases/flex_bandwidth/main.tf
  examples/use-cases/hosted_cloud_aws/main.tf
  examples/use-cases/hosted_cloud_azure/main.tf
  examples/use-cases/hosted_cloud_google/main.tf
  examples/use-cases/marketplace/a_side/main.tf
  examples/use-cases/marketplace/z_side/main.tf
  internal/provider/resource_azure_cloud_router_connection.go
  internal/provider/resource_port_cloud_router_connection.go
Labels: bugfix

#334 Remove disable BGP session and add 20s delay after Azure CRC creation
  CHANGELOG.md
  internal/provider/resource_azure_cloud_router_connection.go
  internal/provider/resource_bgp_session.go
Labels: bugfix

#336 Azure BGP session update: if l3Address is not set, set it based on the values of primarySubnet and secondarySubnet
  docs/resources/packetfabric_cloud_router_bgp_session.md
  examples/use-cases/cloud_router_google_azure/cloud_router_connection_azure.tf
  internal/provider/resource_bgp_session.go
  templates/resources/cloud_router_bgp_session.md.tmpl
Labels: bugfix

#337 Add import verify for packetfabric_cloud_router
  internal/provider/resource_cloud_router_test.go
Labels: acceptance test

#343 Address CVE-2022-27664 and CVE-2022-41723
  go.mod
  go.sum
Labels: reliability

#341 Update CR region attribute, add default values and update docs
  docs/resources/packetfabric_backbone_virtual_circuit.md
  docs/resources/packetfabric_cloud_router.md
  docs/resources/packetfabric_cs_aws_dedicated_connection.md
  docs/resources/packetfabric_marketplace_service.md
  docs/resources/packetfabric_port.md
  internal/provider/resource_aws_request_dedicated_conn.go
  internal/provider/resource_backbone.go
  internal/provider/resource_cloud_router.go
  internal/provider/resource_marketplace.go
  internal/provider/resource_ports.go
Labels: enhancement

#342 Fix Bandwidth reading for each LonghaulType
  docs/resources/packetfabric_backbone_virtual_circuit.md
  internal/provider/resource_backbone.go
Labels: bugfix

#344 Update defaults and schema description
  docs/resources/packetfabric_cloud_router_bgp_session.md
  docs/resources/packetfabric_cloud_router_connection_google.md
  docs/resources/packetfabric_cloud_router_connection_port.md
  docs/resources/packetfabric_cs_aws_dedicated_connection.md
  docs/resources/packetfabric_cs_aws_hosted_marketplace_connection.md
  docs/resources/packetfabric_cs_google_dedicated_connection.md
  docs/resources/packetfabric_port.md
  internal/provider/resource_aws_hosted_mkt.go
  internal/provider/resource_aws_request_dedicated_conn.go
  internal/provider/resource_bgp_session.go
  internal/provider/resource_google_cloud_router_connection.go
  internal/provider/resource_google_dedicated_conn.go
  internal/provider/resource_port_cloud_router_connection.go
  internal/provider/resource_ports.go
Labels: enhancement

#345 resource packetfabric_cs_aws_dedicated_connection: autoneg: Default cannot be set with Required
  CHANGELOG.md
  docs/resources/packetfabric_cs_aws_dedicated_connection.md
  internal/provider/resource_aws_request_dedicated_conn.go
Labels: bugfix

#347 Add Terraform Import support for Port resource
  internal/provider/resource_port_test.go
  internal/provider/resource_ports.go
Labels: enhancement

#348 Add Terraform Import support for Flex Bandwidth resource
  docs/resources/packetfabric_cs_aws_dedicated_connection.md
  docs/resources/packetfabric_flex_bandwidth.md
  internal/provider/resource_flex_bandwidth.go
Labels: enhancement

#346 Add l3_address to bgp response
  docs/data-sources/packetfabric_cloud_router_bgp_session.md
  internal/packetfabric/bgp_session.go
  internal/provider/datasource_bgp_session.go
Labels: enhancement

#351 Fix/350 handle metro dedicated use case
  CHANGELOG.md
  docs/resources/packetfabric_backbone_virtual_circuit.md
  internal/provider/resource_backbone.go
Labels: bugfix

#353 Add rate_limit_in/out, flex_bandwidth_id to packetfabric_backbone_virtual_circuit read()
  internal/packetfabric/services.go
  internal/provider/resource_backbone.go
Labels: enhancement

#349 Add Terraform Import support for Point to Point resource
  internal/packetfabric/point_to_point.go
  internal/provider/resource_point_to_point.go
  internal/provider/resource_point_to_point_test.go
Labels: enhancement

#352 Update read functions for all dedicated/hosted connections + cleanup
  docs/resources/packetfabric_backbone_virtual_circuit_marketplace.md
  docs/resources/packetfabric_ix_virtual_circuit_marketplace.md
  internal/packetfabric/cloud_router_connection.go
  internal/packetfabric/cloud_service_aws.go
  internal/packetfabric/services.go
  internal/provider/datasource_aws_dedicated_conn.go
  internal/provider/datasource_cloud_conn.go
  internal/provider/datasource_locations_zones.go
  internal/provider/provider.go
  internal/provider/resource_aws_dedicated_conn.go
  internal/provider/resource_aws_hosted_conn.go
  internal/provider/resource_aws_hosted_mkt_conn.go
  internal/provider/resource_aws_provision_mkt.go
  internal/provider/resource_azure_dedicated_conn.go
  internal/provider/resource_azure_hosted_conn.go
  internal/provider/resource_azure_provision_mkt.go
  internal/provider/resource_billing.go
  internal/provider/resource_cloud_service_common.go
  internal/provider/resource_google_dedicated_conn.go
  internal/provider/resource_google_hosted_conn.go
  internal/provider/resource_google_provision_mkt.go
  internal/provider/resource_ibm_hosted_conn.go
  internal/provider/resource_ibm_hosted_conn_test.go
  internal/provider/resource_ix_vc.go
  internal/provider/resource_oracle_hosted_conn.go
  internal/provider/resource_oracle_hosted_mkt_conn.go
  internal/provider/resource_oracle_provision_mkt.go
  internal/provider/resource_port.go
  internal/provider/resource_provision_mkt.go
  internal/provider/resource_service_request_provision.go
  internal/provider/resource_service_request_reject.go
  internal/provider/resource_third_party_virtual_circuit.go
Labels: enhancement

#358 Remove existing ACCTests for futher replacement.
  internal/provider/datasource_cloud_locations_test.go
  internal/provider/datasource_locations_markets_test.go
  internal/provider/datasource_locations_regions_test.go
  internal/provider/datasource_port_availability_test.go
  internal/provider/datasource_port_device_info_test.go
  internal/provider/datasource_port_vlan_summary_test.go
  internal/provider/resource_aws_cloud_router_connection_test.go
  internal/provider/resource_cloud_router_test.go
  internal/provider/resource_ibm_hosted_conn_test.go
  internal/provider/resource_ix_vc_test.go
  internal/provider/resource_point_to_point_test.go
  internal/provider/resource_port_loa_test.go
  internal/provider/resource_port_test.go
  internal/provider/resource_third_party_virtual_circuit_test.go
Labels: acceptance test

#359 Deprecate order in packetfabric_cloud_router_bgp_session resource and data-source
  docs/data-sources/packetfabric_cloud_router_bgp_session.md
  docs/resources/packetfabric_cloud_router_bgp_session.md
  examples/resources/packetfabric_cloud_router_bgp_session/resource.tf
  examples/test.tf
  examples/use-cases/cloud_router_aws/cloud_router_connections.tf
  examples/use-cases/cloud_router_aws_google/cloud_router_connection_aws.tf
  examples/use-cases/cloud_router_aws_google/cloud_router_connection_google.tf
  examples/use-cases/cloud_router_google_azure/cloud_router_connection_azure.tf
  examples/use-cases/cloud_router_google_azure/cloud_router_connection_google.tf
  examples/use-cases/cloud_router_google_ipsec/cloud_router_connection_google.tf
  examples/use-cases/cloud_router_google_ipsec/cloud_router_connection_ipsec.tf
  examples/use-cases/cloud_router_ibm_oracle/cloud_router_connection_ibm.tf
  examples/use-cases/cloud_router_ibm_oracle/cloud_router_connection_oracle.tf
  examples/use-cases/cloud_router_module/modules/packetfabric/cloud_router.tf
  internal/packetfabric/bgp_session_test.go
  internal/provider/datasource_bgp_session.go
  internal/provider/resource_bgp_session.go
Labels: enhancement
