Repository PacketFabric/terraform-provider-packetfabric, pull requests merged in 2023-01, with the labels that each got.

#314 Deprecate device_id and site_id and correct optics_diagnostics_lane_values.lane_index in packetfabric_port_device_info
  docs/data-sources/packetfabric_port_device_info.md
  examples/main.tf
  internal/packetfabric/interfaces.go
  internal/provider/datasource_port_device_info.go
  internal/provider/datasource_port_device_info_test.go
Labels: bug, enhancement

#302 Add zone to Cloud Router Connection and Prefixes to BGP Session data sources
  docs/data-sources/packetfabric_cloud_router_bgp_session.md
  docs/data-sources/packetfabric_cloud_router_connections.md
  docs/resources/packetfabric_cloud_router_bgp_session.md
  docs/resources/packetfabric_port.md
  examples/data-sources/packetfabric_cloud_router_bgp_session/data-source.tf
  examples/main.tf
  internal/packetfabric/bgp_session.go
  internal/packetfabric/bgp_session_test.go
  internal/packetfabric/cloud_router_connection.go
  internal/packetfabric/cloud_router_connection_test.go
  internal/provider/datasource_bgp_prefixes.go
  internal/provider/datasource_bgp_session.go
  internal/provider/datasource_cloud_conn.go
  internal/provider/resource_bgp_prefixes.go
  internal/provider/resource_bgp_session.go
Labels: enhancement

#313 Renaming port marketplace resources and data-sources
  docs/data-sources/packetfabric_marketplace_service_requests.md
  docs/resources/packetfabric_marketplace_service_accept_request.md
  docs/resources/packetfabric_marketplace_service_reject_request.md
  examples/data-sources/packetfabric_marketplace_service_port_requests/data-source.tf
  examples/data-sources/packetfabric_marketplace_service_requests/data-source.tf
  examples/main.tf
  examples/resources/packetfabric_marketplace_service_port_accept_request/resource.tf
  examples/resources/packetfabric_marketplace_service_port_reject_request/resource.tf
  examples/use-cases/marketplace/README.md
  examples/use-cases/marketplace/z_side/main.tf
  internal/provider/provider.go
  templates/data-sources/marketplace_service_requests.md.tmpl
  templates/resources/marketplace_service_accept_request.md.tmpl
  templates/resources/marketplace_service_reject_request.md.tmpl
Labels: enhancement

#312 Update required/optional parameters packetfabric_backbone_virtual_circuit
  .github/pull_request_template.md
  CHANGELOG.md
  docs/index.md
  docs/resources/packetfabric_backbone_virtual_circuit.md
  examples/main.tf
  examples/provider/provider.tf
  examples/use-cases/backbone_virtual_circuit/main.tf
  examples/use-cases/backbone_virtual_circuit_mesh/main.tf
  examples/use-cases/cloud_router_aws/provider.tf
  examples/use-cases/cloud_router_aws_google/provider.tf
  examples/use-cases/cloud_router_google_azure/provider.tf
  examples/use-cases/cloud_router_google_ipsec/provider.tf
  examples/use-cases/cloud_router_ibm_oracle/provider.tf
  examples/use-cases/cloud_router_module/main.tf
  examples/use-cases/cloud_router_module/modules/packetfabric/cloud_router.tf
  examples/use-cases/dedicated_cloud_aws/main.tf
  examples/use-cases/hosted_cloud_aws/main.tf
  examples/use-cases/hosted_cloud_azure/main.tf
  examples/use-cases/hosted_cloud_google/main.tf
  examples/use-cases/marketplace/a_side/main.tf
  examples/use-cases/marketplace/z_side/main.tf
  internal/packetfabric/cloud_service.go
  internal/provider/resource_backbone.go
Labels: bug

#315 Fix packetfabric_activitylog data-source
  docs/data-sources/packetfabric_activitylog.md
  internal/packetfabric/activity_log.go
  internal/provider/datasource_activity_log.go
Labels: bugfix

#316 Fix docs for marketplace service port resources & data-source
  docs/data-sources/packetfabric_marketplace_service_port_requests.md
  docs/resources/packetfabric_marketplace_service_port_accept_request.md
  docs/resources/packetfabric_marketplace_service_port_reject_request.md
Labels: documentation

#306 Add DNAT to packetfabric_cloud_router_bgp_session and packetfabric_cloud_router_connection
  CHANGELOG.md
  docs/data-sources/packetfabric_cloud_router_bgp_session.md
  docs/index.md
  docs/resources/packetfabric_cloud_router_bgp_session.md
  docs/resources/packetfabric_cloud_router_connection_aws.md
  docs/resources/packetfabric_cloud_router_connection_azure.md
  docs/resources/packetfabric_cloud_router_connection_google.md
  docs/resources/packetfabric_cloud_router_connection_ibm.md
  docs/resources/packetfabric_cloud_router_connection_oracle.md
  docs/resources/packetfabric_cloud_router_connection_port.md
  examples/README.md
  examples/data-sources/packetfabric_cloud_router_bgp_session/data-source.tf
  examples/provider/provider.tf
  examples/resources/packetfabric_cloud_router_bgp_session/resource.tf
  examples/test.tf
  examples/test_vars.tf
  examples/use-cases/README.md
  examples/use-cases/backbone_virtual_circuit/main.tf
  examples/use-cases/backbone_virtual_circuit/variables.tf
  examples/use-cases/backbone_virtual_circuit_mesh/main.tf
  examples/use-cases/cloud_router_aws/provider.tf
  examples/use-cases/cloud_router_aws_google/cloud_router_connection_google.tf
  examples/use-cases/cloud_router_aws_google/provider.tf
  examples/use-cases/cloud_router_google_azure/cloud_router_connection_google.tf
  examples/use-cases/cloud_router_google_azure/provider.tf
  examples/use-cases/cloud_router_google_ipsec/provider.tf
  examples/use-cases/cloud_router_ibm_oracle/provider.tf
  examples/use-cases/cloud_router_module/main.tf
  examples/use-cases/cloud_router_module/modules/packetfabric/cloud_router.tf
  examples/use-cases/dedicated_cloud_aws/main.tf
  examples/use-cases/hosted_cloud_aws/main.tf
  examples/use-cases/hosted_cloud_aws/variables.tf
  examples/use-cases/hosted_cloud_azure/main.tf
  examples/use-cases/hosted_cloud_azure/variables.tf
  examples/use-cases/hosted_cloud_google/main.tf
  examples/use-cases/hosted_cloud_google/variables.tf
  examples/use-cases/marketplace/a_side/main.tf
  examples/use-cases/marketplace/z_side/main.tf
  internal/packetfabric/bgp_session.go
  internal/packetfabric/cloud_router_connection.go
  internal/packetfabric/cloud_router_connection_test.go
  internal/packetfabric/cloud_router_port.go
  internal/packetfabric/cloud_service_azure.go
  internal/packetfabric/cloud_service_google.go
  internal/provider/datasource_bgp_session.go
  internal/provider/resource_aws_cloud_router_connection.go
  internal/provider/resource_aws_cloud_router_connection_test.go
  internal/provider/resource_azure_cloud_router_connection.go
  internal/provider/resource_bgp_session.go
  internal/provider/resource_cloud_router.go
  internal/provider/resource_google_cloud_router_connection.go
  internal/provider/resource_ibm_route_cloud_connection.go
  internal/provider/resource_oracle_route_cloud_connection.go
  internal/provider/resource_port_cloud_router_connection.go
Labels: new feature
