Repository PacketFabric/terraform-provider-packetfabric, pull requests merged in 2023-04, with the labels that each got.

#414 Update packetfabric_cs_google_hosted_connection with Cloud Side Provisioning option
  docs/data-sources/packetfabric_cs_aws_hosted_connection.md
  docs/data-sources/packetfabric_cs_azure_hosted_connection.md
  docs/data-sources/packetfabric_cs_google_hosted_connection.md
  docs/data-sources/packetfabric_cs_hosted_connection_router_config.md
  docs/data-sources/packetfabric_cs_oracle_hosted_connection.md
  docs/resources/packetfabric_cloud_router_bgp_session.md
  docs/resources/packetfabric_cs_aws_hosted_connection.md
  docs/resources/packetfabric_cs_google_hosted_connection.md
  examples/resources/packetfabric_cs_google_hosted_connection/resource.tf
  examples/test.tf
  examples/test_vars.tf
  examples/use-cases/hosted_cloud_aws/README.md
  examples/use-cases/hosted_cloud_google/README.md
  examples/use-cases/hosted_cloud_google/main.tf
  examples/use-cases/hosted_cloud_google/variables.tf
  internal/packetfabric/cloud_service_aws.go
  internal/packetfabric/cloud_service_google.go
  internal/provider/datasource_hosted_aws_google_azure_oracle_conn.go.go
  internal/provider/datasource_hosted_router_config.go
  internal/provider/resource_aws_hosted_conn.go
  internal/provider/resource_cloud_service_common.go
  internal/provider/resource_google_hosted_conn.go
Labels: new feature

#412 Add new labels page under Guides in Terraform Registry Documentation
  docs/guides/labels.md
  templates/guides/labels.md
Labels: documentation

#416 Remove ASN validation due to overflows int
  internal/provider/cloud_common.go
  internal/provider/resource_aws_hosted_conn.go
  internal/provider/resource_bgp_session.go
  internal/provider/resource_google_hosted_conn.go
Labels: bugfix

#429 Rename packetfabric_port data-source to packetfabric_ports
  docs/data-sources/packetfabric_ports.md
  examples/data-sources/packetfabric_port/data-source.tf
  examples/data-sources/packetfabric_ports/data-source.tf
  examples/test.tf
  internal/provider/provider.go
  templates/data-sources/ports.md.tmpl
Labels: enhancement

#430 Update gcloud bash script in Use Case Examples
  examples/use-cases/cloud_router_aws_google/README.md
  examples/use-cases/cloud_router_aws_google/gcloud_bgp_addresses.sh
  examples/use-cases/cloud_router_aws_google/gcloud_bgp_peer_update.sh
  examples/use-cases/cloud_router_google_azure/README.md
  examples/use-cases/cloud_router_google_azure/gcloud_bgp_addresses.sh
  examples/use-cases/cloud_router_google_azure/gcloud_bgp_peer_update.sh
  examples/use-cases/cloud_router_google_ipsec/README.md
  examples/use-cases/cloud_router_google_ipsec/gcloud_bgp_addresses.sh
  examples/use-cases/cloud_router_google_ipsec/gcloud_bgp_peer_update.sh
Labels: documentation

#431 Update BGP session deletion warning
  internal/provider/resource_bgp_session.go
Labels: enhancement

#433 Check if zone or autoneg are set in packetfabric_port resource
  internal/provider/resource_port.go
Labels: bugfix

#434 Check if Labels are set and fix getLabel in all resources using labels
  internal/provider/labels_common.go
  internal/provider/resource_aws_cloud_router_connection.go
  internal/provider/resource_aws_dedicated_conn.go
  internal/provider/resource_azure_cloud_router_connection.go
  internal/provider/resource_backbone.go
  internal/provider/resource_cloud_router.go
  internal/provider/resource_google_cloud_router_connection.go
  internal/provider/resource_ibm_route_cloud_connection.go
  internal/provider/resource_link_aggregation_groups.go
  internal/provider/resource_oracle_cloud_router_connection.go
  internal/provider/resource_point_to_point.go
  internal/provider/resource_port.go
  internal/provider/resource_port_cloud_router_connection.go
Labels: bugfix

#435 Check if po_number is set in the resource using po_number
  internal/packetfabric/flex_bandwith.go
  internal/provider/resource_aws_cloud_router_connection.go
  internal/provider/resource_aws_hosted_conn.go
  internal/provider/resource_azure_cloud_router_connection.go
  internal/provider/resource_azure_hosted_conn.go
  internal/provider/resource_backbone.go
  internal/provider/resource_cloud_router.go
  internal/provider/resource_flex_bandwidth.go
  internal/provider/resource_google_cloud_router_connection.go
  internal/provider/resource_google_hosted_conn.go
  internal/provider/resource_ibm_hosted_conn.go
  internal/provider/resource_ibm_route_cloud_connection.go
  internal/provider/resource_ipsec_route_cloud_connection.go
  internal/provider/resource_oracle_cloud_router_connection.go
  internal/provider/resource_oracle_hosted_conn.go
  internal/provider/resource_point_to_point.go
  internal/provider/resource_port.go
  internal/provider/resource_port_cloud_router_connection.go
Labels: bugfix

#411 Add streaming events read resource
  docs/resources/packetfabric_streaming_events.md
  examples/packetfabric_streaming_events.py
  examples/resources/packetfabric_streaming_events/resource.tf
  examples/test.tf
  internal/packetfabric/streaming_events.go
  internal/provider/provider.go
  internal/provider/resource_streaming_events.go
  templates/resources/streaming_events.md.tmpl
Labels: new feature

#438 Check if optional parameters are set in cloud router connection resources read()
  internal/provider/resource_aws_cloud_router_connection.go
  internal/provider/resource_ibm_route_cloud_connection.go
  internal/provider/resource_ipsec_route_cloud_connection.go
  internal/provider/resource_oracle_cloud_router_connection.go
  internal/provider/resource_port_cloud_router_connection.go
Labels: bugfix

#437 Update version in docs and examples
  docs/index.md
  examples/provider/provider.tf
  examples/test.tf
  examples/use-cases/backbone_virtual_circuit/main.tf
  examples/use-cases/backbone_virtual_circuit_mesh/main.tf
  examples/use-cases/cloud_router_aws/provider.tf
  examples/use-cases/cloud_router_aws/user-data-ubuntu.sh
  examples/use-cases/cloud_router_aws_google/gcloud_bgp_addresses.sh
  examples/use-cases/cloud_router_aws_google/gcloud_bgp_peer_update.sh
  examples/use-cases/cloud_router_aws_google/provider.tf
  examples/use-cases/cloud_router_aws_google/user-data-ubuntu.sh
  examples/use-cases/cloud_router_aws_oracle_port/provider.tf
  examples/use-cases/cloud_router_google_azure/gcloud_bgp_addresses.sh
  examples/use-cases/cloud_router_google_azure/gcloud_bgp_peer_update.sh
  examples/use-cases/cloud_router_google_azure/provider.tf
  examples/use-cases/cloud_router_google_azure/user-data-ubuntu.sh
  examples/use-cases/cloud_router_google_ipsec/gcloud_bgp_addresses.sh
  examples/use-cases/cloud_router_google_ipsec/gcloud_bgp_peer_update.sh
  examples/use-cases/cloud_router_google_ipsec/provider.tf
  examples/use-cases/cloud_router_google_ipsec/user-data-ubuntu.sh
  examples/use-cases/cloud_router_ibm_oracle/provider.tf
  examples/use-cases/cloud_router_ibm_oracle/user-data-ubuntu.sh
  examples/use-cases/cloud_router_module/main.tf
  examples/use-cases/cloud_router_module/modules/packetfabric/cloud_router.tf
  examples/use-cases/dedicated_cloud_aws/main.tf
  examples/use-cases/flex_bandwidth/main.tf
  examples/use-cases/hosted_cloud_aws/main.tf
  examples/use-cases/hosted_cloud_azure/main.tf
  examples/use-cases/hosted_cloud_google/main.tf
  examples/use-cases/hosted_cloud_ibm/main.tf
  examples/use-cases/marketplace/a_side/main.tf
  examples/use-cases/marketplace/z_side/main.tf
Labels: documentation

#479 Error when user try to update port_circuit_id in Backbone VC resource
  internal/provider/resource_backbone.go
Labels: enhancement

#478 Automate creation of the Release Note from changelog
  .github/workflows/release.yml
Labels: enhancement

#415 Make google_vlan_attachment_name optional when Cloud Settings are used for google hosted cloud
  docs/resources/packetfabric_cs_google_hosted_connection.md
  examples/resources/packetfabric_cs_google_hosted_connection/resource.tf
  examples/use-cases/hosted_cloud_google/main.tf
  internal/provider/resource_google_hosted_conn.go
Labels: enhancement

#482 fix CustomizeDiff and google_keepalive_interval
  examples/use-cases/cloud_router_aws/aws_private_gateway.tf
  internal/packetfabric/cloud_service_aws.go
  internal/provider/resource_aws_cloud_router_connection.go
  internal/provider/resource_google_cloud_router_connection.go
Labels: bugfix
